matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true

    - os: linux
      language: node_js
      node_js: "8"

    - os: windows
      language: node_js
      node_js:  "8"


before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libdbus-1-dev -y; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm test && npm run build:dist && npm run build:electron:linux && npm run build:linux; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then npm test && npm run build:dist:windows && npm run build:electron && npm run build:windows; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then npm test && npm run build:dist && npm run build:electron && npm run build:macos; fi


cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
