name: CI job

on:
  push:
    branches-ignore:
      - crowdin
  pull_request:
    branches-ignore:
      - crowdin

jobs:
  linux_build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18
        uses: actions/setup-node@master
        with:
          version: 18
          cache: npm
      - run: npm ci
      - run: npm test
      - run: npm run build:linux
        shell: bash
        env:
          GITHASH: ${GITHUB_SHA}

  mac_build:
    runs-on: macos-11
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18
        uses: actions/setup-node@master
        with:
          version: 18
          cache: npm
      - run: npm ci
      - run: npm test
      - run: npm run build:macos
        shell: bash
        env:
          GITHASH: ${GITHUB_SHA}

  windows_build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18
        uses: actions/setup-node@master
        with:
          version: 18
          cache: npm
      - name: add git binaries to PATH
        run: |
          echo "C:\Program Files\Git\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\Git\mingw64\libexec\git-core" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          npm config set msvs_version 2022
      - run: npm ci
      - run: npm test
      - run: npm run build:windows
        shell: bash
        env:
          GITHASH: ${GITHUB_SHA}
